### ISSUE TITLE
Webpack without a JS framework

### ISSUE THREAD

**Issue by shelldandy** [survivejs/ama#17]
For example for vanilla static frontend stuff, like having the goodies from gulp but with HMR, for example taking some html/pug/hbs files as entry points

I was fooling around with what this article says but it doesn't support HMR and I also don't have idea on how to _require_ scss and js from the entry html points...

Thanks in advance for the help and also for the book I bought it since webpack 1 era and just 2 days ago i decided to check it again on my leanpub library and was glad to find the book is basically all around updated with new hot tips now that things are settling down.

**Comment by bebraw** [comment]
Hi,

Can you set up a small repository based on what you have so far to study? I can work based on that.

I am currently working on a big update on the book. I hope to complete this work soon. :)

**Comment by shelldandy** [comment]
@bebraw it's not much but I have this so far

https://github.com/mike3run/webpack-static

**Comment by bebraw** [comment]
A couple of notes:

* Instead of `hot: true`, use `hotOnly: true` at `devServer` while debugging.
* Enable `new webpack.NamedModulesPlugin()` for development (doesn't hurt for production either although it will leak path info (might not matter)). This will show which modules fail to patch.
* I noticed neither pug-loader nor pug-html-loader implement HMR `accept`. html-loader doesn't seem to do this either.
* You have pug-loader in the project dependencies but you aren't using it in any way.
* Perhaps a better way would be to load pug through html-webpack-plugin directly? This might get complicated with multiple pages (I think there might be a multi-page plugin somewhere) though.

Give above a go and maybe look into Stack Overflow for more tips. Let me know if you get stuck.

**Comment by bebraw** [comment]
@mike3run Did you progress with this? Perhaps time to close?

**Comment by shelldandy** [comment]
Hey there yeah I'm still working on that but by the time being we can close this and I can open another ticket if I have other doubt thanks a lot for the help and the amazing book
