### ISSUE TITLE
With JSX deprecated, what are the alternatives?

### ISSUE THREAD

**Issue by aliv1** [survivejs/ama#4]

**Comment by bebraw** [comment]
Even though [JSXTransformer was deprecated](https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html), this doesn't mean JSX isn't relevant still. These days you just use a Babel plugin for the transformation. [babel-preset-react](https://www.npmjs.com/package/babel-preset-react) includes it.

JSX is popular for a good reason. Even though there's initial shock involved, it becomes a second nature quite fast as you figure out how the HTMLis structure and JavaScript concepts in it go together. I find it provides a decent balance between older templating based solutions and pure JavaScript. You don't need to learn a special DSL to use it effectively. I think that's its primary strength.

[hyperscript](https://github.com/dominictarr/hyperscript) can be a valid alternative. Rather than inventing a language on top of JavaScript, you just operate within JavaScript itself using a function syntax. If you want to try it with React, consider [hyperscript-helpers](https://github.com/ohanhi/hyperscript-helpers).

**Comment by aliv1** [comment]
Thanks... That clears things up a bit.
