### ISSUE TITLE
A tutorial on testing frameworks

### ISSUE THREAD

**Issue by ishan28mkip** [survivejs/ama#9]
Hi Juho, your books on webpack and react are simply amazing. Unlike other tutorials which teach you how to implement a particular application your tutorials teach us the best practices.

If possible could you try to create a similar book on JS testing frameworks. It is very confusing to understand what Karma, Phantom, Mocha, Chai and should.js actually do, and why there are so many libraries in the testing flow instead of one or two.

**Comment by bebraw** [comment]
Thanks. 👍 

I actually want to write a [testing chapter](https://github.com/survivejs/webpack/issues/87) for the webpack book. That would cover the setup side and the tools you mentioned. If you have further ideas, you could expand there.

I'll also add bits to the testing chapter of the React book as I learn more about the topic. It's true it's not easy given there are so many tools available. That's why I chose more fundamental approach there.

A whole book on testing would be a big undertaking so I doubt I'll get that done anytime soon as I'm still busy pushing the current books forward. You could check out [Greg Kedge's guide](https://gkedge.gitbooks.io/javascript-acceptance-testing/content/), though. The focus is especially on acceptance testing. Incidentally he happens to be one of those guys I met through this effort. 😄
